### ISSUE TITLE
OSError: libquadmath.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by duncancfraser** [ryansb/sklearn-build-lambda#2]
Hey there, I was having trouble with numpy in my serverless project and came across this repo/blog post. I lifted the version of numpy from your zip file, along with the C dependencies included in your lib folder. However, when I deploy my serverless function I'm getting this error:

```
Traceback (most recent call last):
  File "/var/task/add-return-items/handler.py", line 20, in handler
    ctypes.cdll.LoadLibrary(os.path.join(d, f))
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 438, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libquadmath.so.0: cannot open shared object file: No such file or directory
```

which seems to be related to this for loop:

```
 import ctypes

    for d, _, files in os.walk('vendored/lib'):
        for f in files:
            if f.endswith('.a'):
                continue
            ctypes.cdll.LoadLibrary(os.path.join(d, f))
```

As far as I can tell, it seems like ctypes needs `libquadmath.so.0` , however this is one of the files included in the lib I'm trying to load. Any ideas on how to address this?

**Comment by duncancfraser** [comment]
@affablebloke's gist solved my issue by more explicitly loading the .so files in order. thought it would be nice to sort without using an explicit list. https://gist.github.com/affablebloke/9d2ab9bfaee0d318d470b0acec21ae0b
